baseURL      = "https://hackpysec.github.io/cv/"
languageCode = "en-us"
title        = "John Doe - CV"
minVersion   = "0.115.0"

[params]
  description = "NightFolio is a lightweight Hugo theme designed for showcasing professional resumes and portfolios. It uses Tailwind CSS for styling and contains fully modular sections out of the box."

[outputs]
  home = ["HTML"]